### PR TITLE
fix: update of configurations for walking and parcel tracking

### LINKED ISSUE #406: Explaination of parcel tracking does not match configuration explainer
As seen in the pictures above, the text of the parcel tracking updates the cloud every hour when moving, and every 6 hour when not moving. 

Configuration_explainer_text
parcel_tracking_text

### PR DESCRIPTION
**Pull request by KajaKoren**
Update of new configs for the asset tracker, the config for parcel tracking could be tested better, but I have just based it off the idea that it does not trigger when I'm on the bus, but it is tracking when I am moving the thingy:91 around directly. I was thinking on bringing the thingy in my luggage on my next travel to see if this config works as intended, then I get to test it from "start" to "finish", but for now, this was the best I managed to test. closes #406

### CODE REVIEW

File: src/asset/config.ts [hunk 1]
```diff
@@ -24,27 +24,40 @@ export const presetConfigs: Record<
...
+			...defaultConfig,
+			mvres: 60,
+			accito: 30,
+			mvt: 3600,
+			accath: 5,
+			accith: 4.5,
+		},
+		label: 'Driving',
+		description:
+			'Use this to track people activities like driving. It records location every hour when not moving and every 1 minutes when on the move. The accelerometer is configured for driving.',
```
Comment (coderbyheart) [inline src/asset/config.ts]:
```suggestion
			'Use this to track vehicles. It records location every hour when not moving and every 1 minutes when on the move. The accelerometer is configured for vehicles.',
```

File: src/components/Asset/Configuration/Presets.spec.tsx [hunk 2]
```diff
@@ -49,9 +49,17 @@ test('<Presets/>', async () => {
...
 
 	parcel.findOne('button').props.onClick()
 	expect(setNewDesiredConfig).toHaveBeenCalledWith(presetConfigs.parcel.config)
+
+	//Use driving presets
+	const driving = isolated.findOne('[data-test=driving]')
+
+	expect(driving.findOne('h5').content()).toEqual('Driving')
+	expect(driving.findOne('p').content()).toEqual(
+		'Use this to track people activities like driving. It records location every hour when not moving and every 1 minutes when on the move. The accelerometer is configured for driving.',
```
Comment (coderbyheart) [inline src/components/Asset/Configuration/Presets.spec.tsx]:
```suggestion
		'Use this to track vehicles. It records location every hour when not moving and every 1 minutes when on the move. The accelerometer is configured for vehicles.',
```

**Review by coderbyheart — CHANGES_REQUESTED** [review]
Looks good, I suggested a slight change for the vehicle tracking preset.

File: src/components/Asset/Configuration/Presets.spec.tsx (hunk 2 above)
Comment (KajaKoren) [reply src/components/Asset/Configuration/Presets.spec.tsx]: Agreed!

**Comment by coderbyheart** [comment]
Thanks!
